# Pytorch Code-V1

In [ ]:
import torch
import torch.optim as optim

In [ ]:
x1 = torch.FloatTensor([[20], [19], [18.5], [20], [14.5]])
x2 = torch.FloatTensor([[15], [18], [19], [20], [13]])
x3 = torch.FloatTensor([[17], [18.5], [18], [20], [15.5]])
y = torch.FloatTensor([[87], [92.5], [91], [100], [72]])

w1 = torch.zeros(1, requires_grad=True)
w2 = torch.zeros(1, requires_grad=True)
w3 = torch.zeros(1, requires_grad=True)
b = torch.zeros(1, requires_grad=True)

optimizer = optim.SGD([w1, w2, w3, b], lr=1e-3)

for epochs in range(1001):
  hypothesis = w1*x1 + w2*x2 + w3*x3 + b
  cost = torch.mean((hypothesis - y)**2)

  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  if epochs % 100 == 0:
    print("Epoch:  {:3d} / {} W1: {:.5f} W2: {:.5f} W3: {:.5f} b: {:.5f} Hypothesis: {} \
     Cost: {:.5f}".format(epochs, 1000, w1.item(), w2.item(), w3.item(), \
                          b.item(), hypothesis.detach(), cost.item()))

Epoch:    0 / 1000 W1: 3.29000 W2: 3.05400 W3: 3.17770 b: 0.17700 Hypothesis: tensor([[0.],
        [0.],
        [0.],
        [0.],
        [0.]])      Cost: 7918.04980
Epoch:  100 / 1000 W1: 1.74865 W2: 1.52860 W3: 1.69891 b: 0.09543 Hypothesis: tensor([[86.8607],
        [92.2466],
        [92.0523],
        [99.5998],
        [71.6410]])      Cost: 0.29599
Epoch:  200 / 1000 W1: 1.76277 W2: 1.47854 W3: 1.73187 b: 0.09704 Hypothesis: tensor([[86.9715],
        [92.2430],
        [91.9749],
        [99.5610],
        [71.7215]])      Cost: 0.25751
Epoch:  300 / 1000 W1: 1.76842 W2: 1.44138 W3: 1.76171 b: 0.09773 Hypothesis: tensor([[87.0353],
        [92.2342],
        [91.9110],
        [99.5281],
        [71.7836]])      Cost: 0.23425
Epoch:  400 / 1000 W1: 1.76866 W2: 1.41314 W3: 1.78862 b: 0.09770 Hypothesis: tensor([[87.0741],
        [92.2281],
        [91.8630],
        [99.5061],
        [71.8371]])      Cost: 0.21893
Epoch:  500 / 1000 W1: 1.76561 W2: 1.39121 W3: 1.81289 b:

# PyTorch Code-V2

In [ ]:
x = torch.FloatTensor([[20, 15, 17],
                       [19, 18, 18.5],
                       [18.5, 19, 18],
                       [20, 20, 20],
                       [14.5, 13, 15.5]]) #Shape of X: 5X3
y = torch.FloatTensor([[87],
                       [92.5],
                       [91],
                       [100],
                       [72]]) #Shape of y: 5X1

w = torch.zeros((3, 1), requires_grad = True)
b = torch.zeros(1, requires_grad = True)

optimizer = optim.SGD([w, b], lr=1e-3)

for epochs in range(1001):
  hypothesis = x.matmul(w) + b #matmul method is for matrix multiplication
  cost = torch.mean((hypothesis - y)**2)

  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  if epochs % 100 == 0:
    print("Epoch:  {:3d} / {} W1: {:.5f} W2: {:.5f} W3: {:.5f} b: {:.5f} Hypothesis: {} \
     Cost: {:.5f}".format(epochs, 1000, w1.item(), w2.item(), w3.item(), \
                          b.item(), hypothesis.detach(), cost.item()))

Epoch:    0 / 1000 W1: 1.73589 W2: 1.32986 W3: 1.90313 b: 0.17700 Hypothesis: tensor([[0.],
        [0.],
        [0.],
        [0.],
        [0.]])      Cost: 7918.04980
Epoch:  100 / 1000 W1: 1.73589 W2: 1.32986 W3: 1.90313 b: 0.09543 Hypothesis: tensor([[86.8607],
        [92.2466],
        [92.0523],
        [99.5998],
        [71.6410]])      Cost: 0.29599
Epoch:  200 / 1000 W1: 1.73589 W2: 1.32986 W3: 1.90313 b: 0.09704 Hypothesis: tensor([[86.9715],
        [92.2430],
        [91.9749],
        [99.5610],
        [71.7215]])      Cost: 0.25752
Epoch:  300 / 1000 W1: 1.73589 W2: 1.32986 W3: 1.90313 b: 0.09773 Hypothesis: tensor([[87.0353],
        [92.2342],
        [91.9110],
        [99.5281],
        [71.7836]])      Cost: 0.23425
Epoch:  400 / 1000 W1: 1.73589 W2: 1.32986 W3: 1.90313 b: 0.09770 Hypothesis: tensor([[87.0741],
        [92.2281],
        [91.8630],
        [99.5061],
        [71.8371]])      Cost: 0.21893
Epoch:  500 / 1000 W1: 1.73589 W2: 1.32986 W3: 1.90313 b:

In [ ]:
x_new = torch.FloatTensor([[18.5, 13, 20]])
print(x_new.matmul(w) + b)

tensor([[87.5531]], grad_fn=<AddBackward0>)


# TensorFlow Code-V1

In [ ]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

x1 = [20, 19, 18.5, 20, 14.5]
x2 = [15, 18, 19, 20, 13]
x3 = [17, 18.5, 18, 20, 15.5]
y = [87, 92.5, 91, 100, 72]

w1= tf.Variable(tf.random_normal([1], name="w1"))
w2= tf.Variable(tf.random_normal([1], name="w2"))
w3= tf.Variable(tf.random_normal([1], name="w3"))
b= tf.Variable(tf.random_normal([1], name="bias"))

hypothesis = w1*x1 + w2*x2 + w3*x3 + b
cost = tf.reduce_mean(tf.square(hypothesis - y))

# optimizer = tf.train.GradientDescentOptimizer(learning_rate = 1e-3)
# train = optimizer.minimize(cost)
train = tf.train.GradientDescentOptimizer(learning_rate = 1e-3).minimize(cost)

#Run a graph
# with tf.Session() as sess:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

for epoch in range(1001):
  _, w1_val, w2_val, w3_val, b_val, cost_val, hy_val = sess.run([train, w1, w2, w3, b, cost, hypothesis])

  if epoch % 100 == 0:
    print(epoch, w1_val, w2_val, w3_val, b_val, cost_val, hy_val)

Instructions for updating:
non-resource variables are not supported in the long term


0 [2.5878172] [3.4590235] [2.6988244] [0.4972238] 5382.523 [13.330523 16.407396 17.37496  18.28776  12.018327]
100 [1.4832464] [1.9973117] [1.5037504] [0.44061986] 1.2298434 [ 85.60853  92.37916  92.88616 100.11351  71.20758]
200 [1.603632] [1.8162572] [1.5523063] [0.44949582] 0.72371835 [86.150894 92.32926  92.56976  99.89524  71.37284 ]
300 [1.6788374] [1.6894109] [1.5960652] [0.4554656] 0.48268375 [86.50365  92.29028  92.34381  99.742966 71.498825]
400 [1.7241675] [1.5994226] [1.6354357] [0.45933196] 0.36363703 [86.73458  92.2639   92.18463  99.64068  71.600586]
500 [1.7499399] [1.5346624] [1.6708866] [0.46165353] 0.30157265 [86.88425  92.245964 92.07102  99.57197  71.68436 ]
600 [1.7630343] [1.4872726] [1.702827] [0.46281895] 0.26677814 [86.97987 92.23375 91.98869 99.52585 71.75452]
700 [1.768028] [1.4519306] [1.7316203] [0.46310088] 0.24555162 [87.03969 92.2254  91.92796 99.4949  71.81415]
800 [1.7679551] [1.4250226] [1.7575879] [0.4626932] 0.23146722 [87.075874 92.21969  91.88229

# TensorFlow Code-V2

In [ ]:
x1 = tf.placeholder(tf.float32, shape=None) #None means let tensorflow decide a dataset shape automatically
x2 = tf.placeholder(tf.float32, shape=None)
x3 = tf.placeholder(tf.float32, shape=None)
y = tf.placeholder(tf.float32, shape=None)

w1 = tf.Variable(tf.random_normal([1], name="w1"))
w2 = tf.Variable(tf.random_normal([1], name="w2"))
w3 = tf.Variable(tf.random_normal([1], name="w3"))
b = tf.Variable(tf.random_normal([1], name="bias"))

hypothesis = w1*x1 + w2*x2 + w3*x3 + b
cost = tf.reduce_mean(tf.square(hypothesis - y))

train = tf.train.GradientDescentOptimizer(learning_rate = 1e-3).minimize(cost)

# with tf.Session() as sess: #keyword with is optional
sess = tf.Session()
sess.run(tf.global_variables_initializer())

for epoch in range(1001):
  _, w1_val, w2_val, w3_val, b_val, cost_val, hy_val = \
  sess.run([train, w1, w2, w3, b, cost, hypothesis],\
           feed_dict={x1: [20, 19, 18.5, 20, 14.5],
            x2: [15, 18, 19, 20, 13],
            x3: [17, 18.5, 18, 20, 15.5],
            y: [87, 92.5, 91, 100, 72]})
  if epoch % 100 == 0:
    print(epoch, w1_val, w2_val, w3_val, b_val, cost_val, hy_val)

0 [1.4324384] [0.9866314] [2.9196906] [1.457919] 77.96534 [78.177826 83.034195 81.86136  89.42119  66.806885]
100 [1.3033226] [0.90555525] [2.6841483] [1.4319009] 0.72533965 [86.71065  92.1499   91.06088  99.29022  73.706726]
200 [1.3310667] [0.9570671] [2.606753] [1.415692] 0.62827575 [86.70785  92.15809  91.14555  99.31331  73.564095]
300 [1.359146] [1.0001323] [2.5371096] [1.4007467] 0.5508927 [86.71641 92.16341 91.21483 99.32841 73.43651]
400 [1.3865044] [1.0366664] [2.4744306] [1.3868914] 0.48868555 [86.73213 92.16742 91.27312 99.33885 73.32263]
500 [1.4125361] [1.0680522] [2.4180226] [1.3739861] 0.4384436 [86.751656 92.170494 91.32284  99.34614  73.22074 ]
600 [1.4369167] [1.0952924] [2.3672621] [1.3619144] 0.39775485 [86.77289 92.17293 91.36575 99.3513  73.12944]
700 [1.4595045] [1.1191303] [2.3215902] [1.35058] 0.36474183 [86.79439 92.17485 91.40309 99.35498 73.04746]
800 [1.480271] [1.1401244] [2.2804983] [1.3399006] 0.33793256 [86.81545  92.17649  91.435936 99.35775  72.97387

# TensorFlow with Pandas and Numpy

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.DataFrame([{'x1': 20, 'x2': 15, 'x3': 17, 'y': 87},
                   {'x1': 19, 'x2': 18, 'x3': 18.5, 'y': 92.5},
                   {'x1': 18.5, 'x2': 19, 'x3': 18, 'y': 91},
                   {'x1': 20, 'x2': 20, 'x3': 20, 'y': 100},
                   {'x1': 14.5, 'x2': 13, 'x3': 15.5, 'y': 72}])
df

x1  x2    x3      y
0  20.0  15  17.0   87.0
1  19.0  18  18.5   92.5
2  18.5  19  18.0   91.0
3  20.0  20  20.0  100.0
4  14.5  13  15.5   72.0

In [ ]:
x_data = df.iloc[:, 0:-1].to_numpy() #Convert into numpy format
y_data = df.iloc[:, [-1]].to_numpy()

x_data

array([[20. , 15. , 17. ],
       [19. , 18. , 18.5],
       [18.5, 19. , 18. ],
       [20. , 20. , 20. ],
       [14.5, 13. , 15.5]])

In [ ]:
x = tf.placeholder(tf.float32, shape=[None, None])
y = tf.placeholder(tf.float32, shape=[None, None])

w = tf.Variable(tf.random_normal([3, 1]))
b = tf.Variable(tf.random_normal([1]))

hypothesis = tf.matmul(x, w) + b

cost = tf.reduce_mean(tf.square(hypothesis - y))

train = tf.train.GradientDescentOptimizer(learning_rate = 1e-3).minimize(cost)

# with tf.Session() as sess: #keyword with is optional
sess = tf.Session()
sess.run(tf.global_variables_initializer())

for epoch in range(1001):
  _, w_val, b_val, cost_val, hy_val = \
  sess.run([train, w, b, cost, hypothesis],\
           feed_dict={x: x_data, y: y_data})
  if epoch % 100 == 0:
    print(epoch, w_val, b_val, cost_val, hy_val)

0 [[4.296351 ]
 [1.8134253]
 [2.1019554]] [-0.733763] 4098.4023 [[28.920845]
 [25.550373]
 [24.288166]
 [26.436846]
 [19.325893]]
100 [[2.8097427]
 [1.0383152]
 [1.1212955]] [-0.7975949] 2.5789006 [[90.03198 ]
 [92.007324]
 [91.076996]
 [98.57175 ]
 [70.811295]]
200 [[2.5555162]
 [1.2092755]
 [1.2198058]] [-0.7975354] 1.5258538 [[89.19552]
 [92.08999]
 [91.40967]
 [98.89183]
 [70.88421]]
300 [[2.372758 ]
 [1.3133051]
 [1.3088998]] [-0.79565644] 0.9962357 [[88.6152 ]
 [92.1405 ]
 [91.61184]
 [99.10193]
 [70.96937]]
400 [[2.2391348]
 [1.3733683]
 [1.3893452]] [-0.7928644] 0.7131063 [[88.21254 ]
 [92.17392 ]
 [91.732414]
 [99.24292 ]
 [71.06226 ]]
500 [[2.1395957]
 [1.4048582]
 [1.4619521]] [-0.78973407] 0.54952794 [[87.9306  ]
 [92.195984]
 [91.79977 ]
 [99.33763 ]
 [71.15689 ]]
600 [[2.063926 ]
 [1.418023 ]
 [1.5274668]] [-0.78662395] 0.44664964 [[87.73086 ]
 [92.2104  ]
 [91.83264 ]
 [99.40118 ]
 [71.249435]]
700 [[2.005163 ]
 [1.4196601]
 [1.5865729]] [-0.78375065] 0.37662658 [[87.587

In [ ]:
print("Your predicted final exam score is ", sess.run(hypothesis, feed_dict={x: [[19, 19, 18]]}))

Your predicted final exam score is  [[92.75919]]


# Scikit_Learn Code

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

In [ ]:
x_data = df.iloc[:, 0:-1].to_numpy() #Convert into numpy format
y_data = df.iloc[:, [-1]].to_numpy()

In [ ]:
mlr = LinearRegression()
mlr.fit(x_data, y_data)

LinearRegression()

In [ ]:
new_score = [[19, 19, 18]]
mlr.predict(new_score)

array([[91.83655761]])